-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 19:38:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clientes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clientes` ;

-- -----------------------------------------------------
-- Schema clientes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clientes` DEFAULT CHARACTER SET utf8 ;
USE `clientes` ;

-- -----------------------------------------------------
-- Table `clientes`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
   `uf` VARCHAR(2) NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `cidade_id` INT NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_cidade_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_cliente_cidade`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `clientes`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from cidade;

select * from cliente;
