/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mercadojoana.view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author William
 */
public class Principal extends javax.swing.JFrame {

    private CadastroCliente cadastrarCliente = null;
    private TelaSobre telaSobre = null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblSistemaGerenciamento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastrar = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();
        itemRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();
        menuItemManual = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuItemAutores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        lblSistemaGerenciamento.setText("Sistema de Gerenciamento de Vendas");

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-fila.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuItemCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-adicionar-usuário-masculino.png"))); // NOI18N
        menuItemCadastrar.setText("Cadastrar");
        menuItemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemCadastrar);

        itemListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-cardápio.png"))); // NOI18N
        itemListar.setText("Listar");
        itemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarActionPerformed(evt);
            }
        });
        menuClientes.add(itemListar);

        itemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-documento-regular.png"))); // NOI18N
        itemRelatorio.setText("Relatórios");
        menuClientes.add(itemRelatorio);

        jMenuBar1.add(menuClientes);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-comprar.png"))); // NOI18N
        jMenu2.setText("Produtos");
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-treinamento.png"))); // NOI18N
        jMenu3.setText("Funcionarios");
        jMenuBar1.add(jMenu3);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-cartão-de-crédito-sem-contato.png"))); // NOI18N
        menuSobre.setText("Sobre");

        menuItemManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        menuItemManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-gerente-de-informações-do-cliente.png"))); // NOI18N
        menuItemManual.setText("Manual");
        menuItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManualActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemManual);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-suporte-on-line-filled.png"))); // NOI18N
        jMenuItem5.setText("Ajuda");
        menuSobre.add(jMenuItem5);

        menuItemAutores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuItemAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-сharlie-сhaplin.png"))); // NOI18N
        menuItemAutores.setText("Autores");
        menuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAutoresActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemAutores);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(lblSistemaGerenciamento)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSistemaGerenciamento)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarActionPerformed
    }//GEN-LAST:event_itemListarActionPerformed

    private void menuItemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarActionPerformed
        if (cadastrarCliente == null) { // se tiver nulo chama janelan normalmente
            cadastrarCliente = new CadastroCliente();
            desktopPane.add(cadastrarCliente);
            cadastrarCliente.setVisible(true);
        } else {//se ele estiver criado
            if (cadastrarCliente.isVisible()) {
                cadastrarCliente.pack();//volta frame
            } else {
                desktopPane.add(cadastrarCliente);//adicona frame ao JDesktopPane
                cadastrarCliente.setVisible(true);
            }
        }

    }//GEN-LAST:event_menuItemCadastrarActionPerformed

    private void menuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAutoresActionPerformed
        if (telaSobre == null) {
            telaSobre = new TelaSobre();

        }
        telaSobre.setVisible(true);


    }//GEN-LAST:event_menuItemAutoresActionPerformed

    private void menuItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManualActionPerformed
        // TODO add your handling code here:
        try {
           File arquivo = new File(getClass().getResource("/com/mercadojoana/files/loremipsum.pdf").getFile());
            Desktop.getDesktop().open(arquivo);
        } catch (IOException iOException) {
        }

    }//GEN-LAST:event_menuItemManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenuItem itemRelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblSistemaGerenciamento;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuItemAutores;
    private javax.swing.JMenuItem menuItemCadastrar;
    private javax.swing.JMenuItem menuItemManual;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}
