package com.mercadojoana.view;

import com.mercadojoana.control.CadastroClienteControl;
import com.mercadojoana.control.ManualControl;
import com.mercadojoana.control.TelaSobreControl;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author William
 */
public class Principal extends javax.swing.JFrame {
    
    CadastroClienteControl cadastroClienteControl;
    TelaSobreControl telaSobreControl;
    ManualControl manualControl;
    private GerenciarCategoria gerenciarCategoria = null;
    private GerenciarProduto gerenciarProduto = null;
  
    private TelaAjuda telaAjuda = null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cadastroClienteControl = new CadastroClienteControl();
        telaSobreControl = new TelaSobreControl();
        manualControl = new ManualControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSistemaGerenciamento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastrar = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();
        itemRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemGerenciarProduto = new javax.swing.JMenuItem();
        menuItemGerenciarCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();
        menuItemManual = new javax.swing.JMenuItem();
        menuItemAjuda = new javax.swing.JMenuItem();
        menuItemAutores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        lblSistemaGerenciamento.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblSistemaGerenciamento.setText("Sistema de Gerenciamento de Vendas");

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-fila.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuItemCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-adicionar-usuário-masculino.png"))); // NOI18N
        menuItemCadastrar.setText("Cadastrar");
        menuItemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemCadastrar);

        itemListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-cardápio.png"))); // NOI18N
        itemListar.setText("Listar");
        itemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarActionPerformed(evt);
            }
        });
        menuClientes.add(itemListar);

        itemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-documento-regular.png"))); // NOI18N
        itemRelatorio.setText("Relatórios");
        menuClientes.add(itemRelatorio);

        jMenuBar1.add(menuClientes);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-comprar.png"))); // NOI18N
        jMenu2.setText("Produtos");

        menuItemGerenciarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuItemGerenciarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-documentos-do-produto-50.png"))); // NOI18N
        menuItemGerenciarProduto.setText("Gerenciar Produtos");
        menuItemGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGerenciarProduto);

        menuItemGerenciarCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuItemGerenciarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-ordenar-as-respostas-50.png"))); // NOI18N
        menuItemGerenciarCategoria.setText("Gerenciar Categorias");
        menuItemGerenciarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGerenciarCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGerenciarCategoria);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-treinamento.png"))); // NOI18N
        jMenu3.setText("Funcionarios");
        jMenuBar1.add(jMenu3);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-cartão-de-crédito-sem-contato.png"))); // NOI18N
        menuSobre.setText("Sobre");

        menuItemManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        menuItemManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-gerente-de-informações-do-cliente.png"))); // NOI18N
        menuItemManual.setText("Manual");
        menuItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManualActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemManual);

        menuItemAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        menuItemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-suporte-on-line-filled.png"))); // NOI18N
        menuItemAjuda.setText("Ajuda");
        menuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjudaActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemAjuda);

        menuItemAutores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuItemAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mercadojoana/icones/icons8-сharlie-сhaplin.png"))); // NOI18N
        menuItemAutores.setText("Autores");
        menuItemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAutoresActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemAutores);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSistemaGerenciamento)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane)
                .addGap(18, 18, 18)
                .addComponent(lblSistemaGerenciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarActionPerformed
    }//GEN-LAST:event_itemListarActionPerformed

    private void menuItemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarActionPerformed
        cadastroClienteControl.abrirTelaCadastroClienteAction();

    }//GEN-LAST:event_menuItemCadastrarActionPerformed
    

    private void menuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAutoresActionPerformed
        telaSobreControl.chamandoTelaSobre();
        

    }//GEN-LAST:event_menuItemAutoresActionPerformed
    
   

    private void menuItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManualActionPerformed
        manualControl.abrirArquivoManualAction();

    }//GEN-LAST:event_menuItemManualActionPerformed
    
   

    private void menuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjudaActionPerformed
        // TODO add your handling code here:
        if (telaAjuda == null) {
            telaAjuda = new TelaAjuda();
            
        }
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_menuItemAjudaActionPerformed

    private void menuItemGerenciarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarCategoriaActionPerformed
        // TODO add your handling code here:
        if (gerenciarCategoria == null) {
            gerenciarCategoria = new GerenciarCategoria();
            desktopPane.add(gerenciarCategoria);
            gerenciarCategoria.setVisible(true);
        } else {
            if (gerenciarCategoria.isVisible()) {
                gerenciarCategoria.pack();
            } else {
                desktopPane.add(gerenciarCategoria);
                gerenciarCategoria.setVisible(true);
            }
        }
        

    }//GEN-LAST:event_menuItemGerenciarCategoriaActionPerformed

    private void menuItemGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGerenciarProdutoActionPerformed
        // TODO add your handling code here:
        if (gerenciarProduto == null) {
            gerenciarProduto = new GerenciarProduto();
            desktopPane.add(gerenciarProduto);
            gerenciarProduto.setVisible(true);
        } else {
            if (gerenciarProduto.isVisible()) {
                gerenciarProduto.pack();
            } else {
                desktopPane.add(gerenciarProduto);
                gerenciarProduto.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_menuItemGerenciarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JDesktopPane desktopPane = new javax.swing.JDesktopPane();
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenuItem itemRelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblSistemaGerenciamento;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuItemAjuda;
    private javax.swing.JMenuItem menuItemAutores;
    private javax.swing.JMenuItem menuItemCadastrar;
    private javax.swing.JMenuItem menuItemGerenciarCategoria;
    private javax.swing.JMenuItem menuItemGerenciarProduto;
    private javax.swing.JMenuItem menuItemManual;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}
